version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - .env
